load: # need to change these to correspond to your folders
   home_dir:   /home/sam/Downloads/kid_phase_fit/test_data/
   save_dir:   /home/sam/Downloads/kid_phase_fit/
   fig_dir:    /home/sam/Downloads/kid_phase_fit/
   sweep_name: toltec0_017068

save: 
# can run these all in the same instance,
# set to True (False) to turn each option on (off)
   use_save_fig:  False
   use_save_pdf:  False
   use_save_file: False
   save_name:     test1

weight:
   window_Qr: 12000
   
   # optional, options are lorentz OR
   # gauss, OR
   # leave blank to turn option off
   weight_type:

flag_settings:
   a_predict_guess:     0.2  # nonlinearity parameter to set to, default to 0.2
   a_predict_threshold: 0.25 # nonlinearity parameter guess accuracy, default to 0.25
   pherr_threshold:     0.25 # related to the percent the fit is off from the data, default is 0.15
   pherr_threshold_num: 5    # number of points allowed above pherr threshold, default to 10
   
   
fit_settings:
   # leave powlist_start(end) blank to fit all drive attenuations
   powlist_start: 9 # int
   powlist_end:  -1 # int
   numspan:       1 # default: 2
   
   # options: all # for all tones  OR 
   # any list of tones/integers OR 
   # a single tone/integer
   tone_range: [0,1,2,3,4,5,6,7,8,9,10] #all
